language: node_js

node_js:
    - 10
    - node
    - lts/*

arch:
   - amd64
   - ppc64le   

addons:
   apt:
    update: true
    packages: 
       - build-essential 
       - npm 
       - wget 

jobs:
  allow_failures:
  - node_js: node
  
